import { type SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mySidebar: [
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Platforms",
      items: [
        {
          type: "category",
          label: "Android",
          items: [{ type: "autogenerated", dirName: "android" }],
        },
        {
          type: "category",
          label: "iOS",
          items: [
            { type: "autogenerated", dirName: "ios" },
            {
              type: "category",
              label: "iOS 6.x (New Structure)",
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "Overview",
                  items: [
                    {
                      type: "doc",
                      id: "ios/open-source/overview/index"
                    },
                    {
                      type: "doc",
                      id: "ios/open-source/overview/key-features"
                    },
                    {
                      type: "doc",
                      id: "ios/open-source/overview/requirements"
                    },
                    {
                      type: "doc",
                      id: "ios/open-source/overview/architecture"
                    }
                  ],
                },
                {
                  type: "category",
                  label: "Getting Started",
                  items: [],
                },
                {
                  type: "category",
                  label: "Core Concepts",
                  items: [],
                },
                {
                  type: "category",
                  label: "Automatic Instrumentation",
                  items: [],
                },
                {
                  type: "category",
                  label: "Manual Instrumentation",
                  items: [],
                },
                {
                  type: "category",
                  label: "Advanced Features",
                  items: [],
                },
                {
                  type: "category",
                  label: "Best Practices",
                  items: [],
                },
                {
                  type: "category",
                  label: "API Reference",
                  items: [],
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Unity",
          items: [{ type: "autogenerated", dirName: "unity" }],
        },
        {
          type: "category",
          label: "React Native",
          items: [{ type: "autogenerated", dirName: "react-native" }],
        },
        {
          type: "category",
          label: "Flutter",
          items: [{ type: "autogenerated", dirName: "flutter" }],
        },
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Essentials",
      items: [
        {
          type: "category",
          label: "Product Overview",
          items: [{ type: "autogenerated", dirName: "product" }],
        },
        {
          type: "category",
          label: "Best Practices",
          items: [{ type: "autogenerated", dirName: "best-practices" }],
        },
        {
          type: "link",
          href: "https://www.youtube.com/channel/UC8EjpY1ol3QGdp2qk1uZARQ",
          label: "Tutorials",
        },  
      ],
    },
    {
      type: "category",
      label: "OpenTelemetry",
      items: [{ type: "autogenerated", dirName: "open-telemetry" }],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Data Forwarding",
      items: [
        {
          type: "category",
          label: "Data Destinations",
          items: [{ type: "autogenerated", dirName: "data-destinations" }],
        },
        {
          type: "category",
          label: "Custom Metrics API",
          items: [{ type: "autogenerated", dirName: "custom-metrics-api" }],
        },
        {
          type: "category",
          label: "Metrics API",
          items: [{ type: "autogenerated", dirName: "embrace-api" }],
        },
        {
          type: "category",
          label: "Spans API",
          items: [{ type: "autogenerated", dirName: "spans-api" }],
        },
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [{ type: "autogenerated", dirName: "features" }],
    },
    {
      type: "category",
      label: "Partnerships",
      items: [{ type: "autogenerated", dirName: "partners" }],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Legal",
      items: [
        {
          type: "doc",
          id: "privacy-policy",
        },
        {
          type: "doc",
          id: "terms-of-service",
        },
        {
          type: "doc",
          id: "dpa/index",
        },
      ],
    },
  ],
};

module.exports = sidebars;
