import { type SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mySidebar: [
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "OpenTelemetry",
      items: [{ type: "autogenerated", dirName: "open-telemetry" }],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Instrumentation",
      items: [
            {
              type: "category",
              label: "Android",
              items: [{ type: "autogenerated", dirName: "android" }],
            },
            {
              type: "category",
              label: "iOS",
              items: [
                { type: "autogenerated", dirName: "ios" },
                {
                  type: "category",
                  label: "iOS 6.x (New Structure)",
                  collapsed: true,
                  items: [
                    {
                      type: "category",
                      label: "Overview",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/overview/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/overview/key-features"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/overview/requirements"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/overview/architecture"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual getting started content
                    {
                      type: "category",
                      label: "Getting Started",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/getting-started/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/getting-started/installation"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/getting-started/basic-setup"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/getting-started/configuration-options"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/getting-started/migration-guide"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual core concepts content
                    {
                      type: "category",
                      label: "Core Concepts",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/core-concepts/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/core-concepts/sessions"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/core-concepts/traces-spans"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/core-concepts/logs"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/core-concepts/user-identification"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual automatic instrumentation content
                    {
                      type: "category",
                      label: "Automatic Instrumentation",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/overview/index", // Reusing existing doc as placeholder
                          label: "Automatic Instrumentation Placeholder"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual manual instrumentation content
                    {
                      type: "category",
                      label: "Manual Instrumentation",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/manual-instrumentation/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/manual-instrumentation/custom-traces",
                          label: "Traces"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/manual-instrumentation/custom-logging",
                          label: "Logging"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/manual-instrumentation/error-handling"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/manual-instrumentation/performance-monitoring"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual advanced features content
                    {
                      type: "category",
                      label: "Advanced Features",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/advanced-features/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/advanced-features/opentelemetry-export"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/advanced-features/network-body-capture"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/advanced-features/user-personas"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/advanced-features/last-run-end-state"
                        }
                      ],
                    },
                    // TODO: replace placeholder with actual best practices content
                    {
                      type: "category",
                      label: "Best Practices",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/performance-optimization"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/security-considerations"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/debugging-tips"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/common-patterns"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/best-practices/dsym-uploads"
                        }
                      ],
                    },
                    // API reference section is now complete
                    {
                      type: "category",
                      label: "API Reference",
                      items: [
                        {
                          type: "doc",
                          id: "ios/open-source/api-reference/index"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/api-reference/embrace-client"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/api-reference/configuration"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/api-reference/capture-services"
                        },
                        {
                          type: "doc",
                          id: "ios/open-source/api-reference/utility-classes"
                        }
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Unity",
              items: [{ type: "autogenerated", dirName: "unity" }],
            },
            {
              type: "category",
              label: "React Native",
              items: [{ type: "autogenerated", dirName: "react-native" }],
            },
            {
              type: "category",
              label: "Flutter",
              items: [{ type: "autogenerated", dirName: "flutter" }],
            },
        {
          type: "doc",
          label: "Data Marshaling and Transmission",
          id: "product/data-marshaling-and-transmission",
        },
        {
          type: "doc",
          label: "Video Recording and Apple's Policy",
          id: "product/video-recording-and-apples-policy",
        },
      ]
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Dashboard",
      items: [
        {
          type: "category",
          label: "User Sessions",
          items: [{ type: "autogenerated", dirName: "features/user-sessions" }],
        },
        {
          type: "category",
          label: "Boards",
          items: [{ type: "autogenerated", dirName: "features/dashboards" }],
        },
        {
          type: "category",
          label: "Traces",
          items: [{ type: "autogenerated", dirName: "features/traces" }],
        },
        {
          type: "category",
          label: "Network",
          items: [{ type: "autogenerated", dirName: "features/network" }],
        },
            {
              type: "category",
              label: "Crashes",
              items: [
                {
                  type: "doc",
                  label: "Crash Reporting",
                  id: "features/crash-reporting"
                },
                {
                  type: "doc",
                  label: "Crash Tagging",
                  id: "product/tagging"
                },
              ],
            },
            {
              type: "category",
              label: "Issues",
              items: [
                {
                  type: "doc",
                  label: "Issue Monitoring",
                  id: "product/issue-monitoring-and-work-flow"
                },
                {
                  type: "doc",
                  label: "ANR Reporting",
                  id: "features/anr-reporting"
                },
              ],
            },
            {
              type: "doc",
              label: "Logs",
              id: "features/error-logs-tracking"
            },
            {
              type: "doc",
              label: "Release Health",
              id: "features/release-health"
            },
        {
          type: "category",
          label: "Developer Features",
          items: [
            {
              type: "doc",
              label: "Alerting",
              id: "features/alerting"
            },
            {
              type: "doc",
              label: "Webhooks",
              id: "best-practices/webhooks"
            },

            {
              type: "doc",
              label: "Single Sign-On",
              id: "product/sso"
            },
            {
              type: "doc",
              label: "User Permissions",
              id: "product/permissions"
            },
            {
              type: "doc",
              label: "Limiting Traffic in Embrace",
              id: "best-practices/sampling"
            },
          ],
        },
        {
          type: "link",
          href: "https://www.youtube.com/channel/UC8EjpY1ol3QGdp2qk1uZARQ",
          label: "Tutorials",
        },  
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Data Forwarding",
      items: [
        {
          type: "category",
          label: "Metrics",
          items: [
            {
              type: "category",
              label: "Data Destinations",
              items: [{ type: "autogenerated", dirName: "data-destinations" }],
            },
            {
              type: "category",
              label: "Custom Metrics API",
              items: [{ type: "autogenerated", dirName: "custom-metrics-api" }],
            },
            {
              type: "category",
              label: "Metrics API",
              items: [{ type: "autogenerated", dirName: "embrace-api" }],
            },
          ],
        },
        {
          type: "category",
          label: "Spans",
          items: [
            {
              type: "doc",
              label: "Network Span Forwarding",
              id: "product/network-spans-forwarding"
            },
            {
              type: "category",
              label: "Spans API",
              items: [{ type: "autogenerated", dirName: "spans-api" }],
            },
          ],
        },
        {
          type: "category",
          label: "Partnerships",
          items: [{ type: "autogenerated", dirName: "partners" }],
        },    
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Policies and Legal",
      items: [
        {
          type: "doc",
          id: "product/region",
        },
        {
          type: "doc",
          id: "privacy-policy",
        },
        {
          type: "doc",
          id: "terms-of-service",
        },
        {
          type: "doc",
          id: "dpa/index",
        },
      ],
    },
  ],
};

module.exports = sidebars;