import { type SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mySidebar: [
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "OpenTelemetry",
      items: [{ type: "autogenerated", dirName: "open-telemetry" }],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Instrumentation",
      items: [
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "SDKs",
          items: [
            {
              type: "category",
              label: "Android",
              items: [{ type: "autogenerated", dirName: "android" }],
            },
            {
              type: "category",
              label: "iOS",
              items: [{ type: "autogenerated", dirName: "ios" }],
            },
            {
              type: "category",
              label: "Unity",
              items: [{ type: "autogenerated", dirName: "unity" }],
            },
            {
              type: "category",
              label: "React Native",
              items: [{ type: "autogenerated", dirName: "react-native" }],
            },
            {
              type: "category",
              label: "Flutter",
              items: [{ type: "autogenerated", dirName: "flutter" }],
            },
          ]
        },
        {
          type: "doc",
          label: "Data Marshaling and Transmission",
          id: "product/data-marshaling-and-transmission",
        },
        {
          type: "doc",
          label: "Video Recording and Apple's Policy",
          id: "product/video-recording-and-apples-policy",
        },
        
      ]
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Dashboard",
      items: [
        {
          type: "category",
          label: "App Visualization",
          items: [
            {
              type: "category",
              label: "User Sessions",
              items: [
                {
                  type: "doc",
                  label: "User Session Insights",
                  id: "features/user-session-insights"
                },
                {
                  type: "doc",
                  label: "Filtering Sessions",
                  id: "product/sessions"
                },
              ],
            },
            {
              type: "doc",
              label: "Traces",
              id: "features/traces"
            },
            {
              type: "category",
              label: "Network",
              items: [
                {
                  type: "doc",
                  label: "Network Monitoring",
                  id: "features/network-monitoring"
                },
                {
                  type: "doc",
                  label: "Webhooks",
                  id: "best-practices/webhooks"
                },
                {
                  type: "doc",
                  label: "GraphQL Requests",
                  id: "best-practices/graphql"
                },
              ],
            },
            {
              type: "category",
              label: "Crashes",
              items: [
                {
                  type: "doc",
                  label: "Crash Reporting",
                  id: "features/crash-reporting"
                },
                {
                  type: "doc",
                  label: "Crash Tagging",
                  id: "product/tagging"
                },
              ],
            },
            {
              type: "category",
              label: "Issues",
              items: [
                {
                  type: "doc",
                  label: "Issue Monitoring",
                  id: "product/issue-monitoring-and-work-flow"
                },
                {
                  type: "doc",
                  label: "ANR Reporting",
                  id: "features/anr-reporting"
                },
              ],
            },
            {
              type: "doc",
              label: "Logs",
              id: "features/error-logs-tracking"
            },
          ],
        },
        {
          type: "category",
          label: "Developer Features",
          items: [
            {
              type: "doc",
              label: "Widgets",
              id: "product/custom-dashboards"
            },
            {
              type: "doc",
              label: "Alerting",
              id: "features/alerting"
            },
            {
              type: "doc",
              label: "Single Sign-On",
              id: "product/sso"
            },
            {
              type: "doc",
              label: "User Permissions",
              id: "product/permissions"
            },
            {
              type: "doc",
              label: "Limiting Traffic in Embrace",
              id: "best-practices/sampling"
            },
          ],
        },
        {
          type: "link",
          href: "https://www.youtube.com/channel/UC8EjpY1ol3QGdp2qk1uZARQ",
          label: "Tutorials",
        },  
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Data Forwarding",
      items: [
        {
          type: "category",
          label: "Metrics",
          items: [
            {
              type: "category",
              label: "Data Destinations",
              items: [{ type: "autogenerated", dirName: "data-destinations" }],
            },
            {
              type: "category",
              label: "Custom Metrics API",
              items: [{ type: "autogenerated", dirName: "custom-metrics-api" }],
            },
            {
              type: "category",
              label: "Metrics API",
              items: [{ type: "autogenerated", dirName: "embrace-api" }],
            },
          ],
        },
        {
          type: "category",
          label: "Spans",
          items: [
            {
              type: "doc",
              label: "Network Span Forwarding",
              id: "product/network-spans-forwarding"
            },
            {
              type: "category",
              label: "Spans API",
              items: [{ type: "autogenerated", dirName: "spans-api" }],
            },
          ],
        },
        {
          type: "category",
          label: "Partnerships",
          items: [{ type: "autogenerated", dirName: "partners" }],
        },    
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Policies and Legal",
      items: [
        {
          type: "doc",
          id: "product/region",
        },
        {
          type: "doc",
          id: "privacy-policy",
        },
        {
          type: "doc",
          id: "terms-of-service",
        },
        {
          type: "doc",
          id: "dpa/index",
        },
      ],
    },
  ],
};

module.exports = sidebars;
