name: CI - Markdown Lint

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  rumdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        python-version: "3.13"

      - name: Install rumdl
        run: pip install -U rumdl

      - name: rumdl check
        run: rumdl check --output-format github || exit 0
