name: "CI - Deploy"

on:
  push:
    branches: [ main ]
  release:
    types: [ released ]
  pull_request:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deployment event
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.GH_EMBRACE_DOCS_INTERNAL_TOKEN }} # zizmor: ignore[secrets-outside-env]
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'embrace-io',
              repo: 'embrace-docs-internal',
              workflow_id: 'ci-docusaurus.yml',
              ref: 'master',
              inputs: {event_name: '${{ github.event_name }}', event_number: '${{ github.event.number }}'}
            })
